name: CI/CD CN001/SN001 Firmware Deployment Procedure

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      firmware_path: ${{ steps.archive.outputs.firmware_path }}
      release_date: ${{ steps.set-date.outputs.release_date }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      
      - name: Set up Python
        uses: actions/setup-python@v1
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip install platformio
      
      - name: Install platformIO libraries
        run: sudo pio lib install
      
      - name: Run PlatformIO
        run: ./flash.sh compile
      
      - name: Archive Firmware
        id: archive
        run: |
          mkdir -p firmware
          cp .pio/build/compile/firmware.bin firmware/firmware.bin
          echo "firmware_path=firmware/firmware.bin" >> $GITHUB_OUTPUT

      - name: Set release date
        id: set-date
        run: |
          sudo timedatectl set-timezone Australia/Melbourne
          echo "release_date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

  deploy-to-apache:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Download firmware artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: firmware

      - name: Set up SSH key for Apache server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Upload to Apache server via SCP
        run: |
          scp -P 5823 -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
              firmware/firmware.bin \
              datafarm@45.79.239.100:/var/www/html/firmware_${{ github.run_number }}.bin

  create-release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Download firmware artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: firmware

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.release_date }}
          release_name: ${{ needs.build.outputs.release_date }}
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: firmware/firmware.bin
          asset_name: site-v${{ github.run_number }}.bin
          asset_content_type: application/octet-stream